exports_files(
    [
        "Doxygen-mcss",
    ],
    visibility = ["@mcss//:__pkg__"],
)

filegroup(
    name = "config",
    srcs = [
        "Doxyfile",
        "Doxyfile-mcss",
    ],
    visibility = ["@mcss//:__pkg__"],
)
