load("@local_config//:defs.bzl", "PROJECT_DEFAULT_COPTS")

cc_binary(
    name = "turtle_dummy",
    srcs = [
        "turtle.cpp",
    ],
    copts = PROJECT_DEFAULT_COPTS,
    deps = [
        "//:turtle",
    ],
)
