name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BAZEL_VERSION: "4.2.1"
  GCC_VERSION: 11
  LLVM_VERSION: 13

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [gcc, clang, asan, tsan, ubsan]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup compiler info
      run: |
        if [[ "${{ matrix.config }}" == "clang"  ]]; then
          clang --version
          echo "compiler=clang" >> $GITHUB_ENV
        else
          sudo apt-get update
          sudo apt-get install -y g++-${GCC_VERSION}
          echo "compiler=g++-${GCC_VERSION}" >> $GITHUB_ENV
        fi

    - name: Print compiler info
      run: |
        ${{ env.compiler }} --version

    - id: cache-bazel-install
      uses: actions/cache@v2
      with:
        path: |
          ~/bin/bazel*
          ~/.bazel
        key: ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}

    - id: cache-bazel-out
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
        key: ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}-${{ matrix.config }}-${{ github.sha }}
        restore-keys: |
          ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}-${{ matrix.config }}-

    - name: Setup Bazel
      run: |
        if [[ "${{ steps.cache-bazel-install.outputs.cache-hit }}" != "true" ]]; then
          OS=linux
          URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${OS}-x86_64.sh"

          wget -O install.sh "${URL}"
          chmod +x install.sh
          ./install.sh --user
          rm -f install.sh
        fi

        cat .bazelrc.ci >> .bazelrc
        bazel --version

    - name: Build and Test
      run: |
        export CC=${{ env.compiler }}
        bazel build --config=${{ matrix.config }} //...
        bazel test --config=${{ matrix.config }} //...

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install clang-format ${{ env.LLVM_VERSION }}
      run: |
        sudo .github/workflows/llvm.sh ${LLVM_VERSION}
        sudo apt-get install -y clang-format-${LLVM_VERSION}
        clang-format-${LLVM_VERSION} --version

    - name: Run clang-format
      run: |
        ./run_format.sh clang-format-${LLVM_VERSION}
        git --no-pager diff
        git update-index --really-refresh
        git --no-pager diff

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install clang-tidy ${{ env.LLVM_VERSION }}
        run: |
          sudo .github/workflows/llvm.sh ${LLVM_VERSION}
          sudo apt-get install -y clang-tidy-${LLVM_VERSION}

      - name: Link clang-tidy to clang-tidy-${{ env.LLVM_VERSION }}
        run: |
          sudo ln -s $(which clang-tidy-13) /usr/bin/clang-tidy
          clang-tidy --version

      - id: cache-bazel-install
        uses: actions/cache@v2
        with:
          path: |
            ~/bin/bazel*
            ~/.bazel
          key: ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}

      - id: cache-bazel-out
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}-${{ matrix.config }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.os }}-bazel-${{ env.BAZEL_VERSION }}-${{ matrix.config }}-

      - name: Setup Bazel
        run: |
          if [[ "${{ steps.cache-bazel-install.outputs.cache-hit }}" != 'true' ]]; then
            OS=linux
            URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${OS}-x86_64.sh"

            wget -O install.sh "${URL}"
            chmod +x install.sh
            ./install.sh --user
            rm -f install.sh
          fi

          cat .bazelrc.ci >> .bazelrc

      - name: Lint
        env:
          CC: clang
          CXX: clang++
        run: |
          bazel build --config=clang-tidy //...
